# Generated by Django 4.1.2 on 2022-10-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_alter_prestamos_fecprestamo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamos',
            name='idLibro',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='prestamos',
            name='idUsuario',
            field=models.CharField(max_length=10),
        ),
    ]
