# Generated by Django 4.1.2 on 2022-10-11 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_alter_prestamos_idlibro_alter_prestamos_idusuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestamos',
            options={'verbose_name': 'Prestamos', 'verbose_name_plural': 'Prestamos'},
        ),
    ]
